### ISSUE TITLE
Pirâmide

### ISSUE THREAD

**Issue by nandomaciel** [jessielyoliveira/Lab-01#3]
Verificar calculo da pirâmide e comentar variáveis.

**Comment by jessielyoliveira** [comment]
Tá dando bug onde? Desenvolvi como o site ensinou. 
Tá errado é?
Vou comentar as variáveis.

**Comment by nandomaciel** [comment]
Não ta errado, era na linkagem dos arquivos que dava erro, mas a função para o calculo da area piramide deve ser revista pois ela foi comentada para facilitar a linkagem dos arquivos. @jessielyoliveira #7
[areaPiramide](https://github.com/jessielyoliveira/Lab-01/blob/fernando/src/area.cpp#L51)
