### ISSUE TITLE
Make

### ISSUE THREAD

**Issue by jessielyoliveira** [jessielyoliveira/Lab-01#9]
Tentar rodar o make no meu pc deu esse erro.

jessiely@jessiely:~/Documentos/IMD0030_LP1/Lab01$ make
g++ -Wall -pedantic -std=c++11 -ansi -g ./build/*.o -o ./bin/geometria
/usr/bin/ld: a arquitetura i386:x86-64 do arquivo de entrada `./build/area.o' é incompatível com a saída i386
/usr/bin/ld: a arquitetura i386:x86-64 do arquivo de entrada `./build/calcarea.o' é incompatível com a saída i386
/usr/bin/ld: a arquitetura i386:x86-64 do arquivo de entrada `./build/calcperimetro.o' é incompatível com a saída i386
/usr/bin/ld: a arquitetura i386:x86-64 do arquivo de entrada `./build/calcvolume.o' é incompatível com a saída i386
/usr/bin/ld: a arquitetura i386:x86-64 do arquivo de entrada `./build/main.o' é incompatível com a saída i386
/usr/bin/ld: a arquitetura i386:x86-64 do arquivo de entrada `./build/perimetro.o' é incompatível com a saída i386
/usr/bin/ld: a arquitetura i386:x86-64 do arquivo de entrada `./build/volume.o' é incompatível com a saída i386
/usr/bin/ld: ./build/area.o: classe do arquivo ELFCLASS64 é incompatível com ELFCLASS32
/usr/bin/ld: falha no link final: Arquivo no formato errado
collect2: error: ld returned 1 exit status
Makefile:32: recipe for target 'bin/geometria' failed
make: *** [bin/geometria] Error 1

**Comment by nandomaciel** [comment]
Vc tem que criar as pastas bin build doc lib test

**Comment by jessielyoliveira** [comment]
Já deu certo :+1:
